backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://elijah.io

collections:
  - name: "politics"
    label: "Politics"
    folder: "content"
    create: true
    slug: "{{path}}"
    editor:
     preview: false
    filter: {field: "category", value: "Politics"}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Politics", "Technology"] }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }

  - name: "tech"
    label: "Technology"
    folder: "content"
    create: true
    slug: "{{path}}"
    editor:
     preview: false
    filter: {field: "category", value: "Technology"}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Politics", "Technology"] }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }